services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
     - /home/selkhao/data/mariadb:/var/lib/mysql
    networks:
     - inception
    restart: unless-stopped
    env_file:
     - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - /home/selkhao/data/wordpress:/var/www/html
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb_data
  wordpress_data:
    name: wordpress_data
